#!/usr/bin/env node
/**
 * @license Copyright 2017 Palantir Technologies, Inc. All rights reserved.
 * @fileoverview Generates data for packages/docs-app
 */

// @ts-check

import { Documentalist, KssPlugin, MarkdownPlugin, TypescriptPlugin } from "@documentalist/compiler";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { cwd } from "node:process";
import semver from "semver";

import { Classes } from "@blueprintjs/core";

import { hooks, markedRenderer } from "./markdownRenderer.mjs";
import { buildNavTree, buildRouteMap, fixPageRoutes } from "./navHelpers.mjs";

/** Run Documentalist on Sass, TypeScript, and package.json files in these packages */
const LIBRARY_PACKAGES = ["core", "datetime", "datetime2", "icons", "select", "table", "labs"];

/** This package is expected to have the markdown "navPage" */
const DOCS_PACKAGE = "docs-app";

/** Run Documentalist on Markdown files in these packages */
const LIBRARY_AND_DOCS_PACKAGES = [...LIBRARY_PACKAGES, DOCS_PACKAGE];

console.info(`[docs-data] compiling documentation for library packages: ${LIBRARY_PACKAGES.join(", ")}`);

// assume we are running from packages/docs-app
const monorepoRootDir = resolve(cwd(), "../../");
const generatedSrcDir = resolve(cwd(), "./src/generated");
const docsDataFilePath = join(generatedSrcDir, "docs.json");

try {
    if (!existsSync(generatedSrcDir)) {
        mkdirSync(generatedSrcDir);
    }
    await generateDocumentalistData();
    await generateNpmVersions();
} catch (err) {
    console.error("[docs-data] ERROR:", err);
    process.exit(1);
}

console.info(`[docs-data] successfully generated docs.json and npm-data.json`);

async function generateDocumentalistData(): Promise<void> {
    const documentalist = new Documentalist({
        markdown: {
            hooks,
            renderer: markedRenderer,
        },
        // must mark our @Decorator APIs as reserved so we can use them in code samples
        reservedTags: ["import", "ContextMenuTarget", "HotkeysTarget", "param", "returns", "use"],
        sourceBaseDir: monorepoRootDir,
    })
        .use(".mdx", {
            compile: files =>
                // HACKHACK: special case for Windows environment
                // see https://github.com/palantir/documentalist/issues/98
                process.platform === "win32" ? files.map(file => file.read().replace(/\r\n/g, "\n")) : files,
        })
        .use(".mdx", new MarkdownPlugin({ navPage: "_nav" }))
        .use(
            /\.tsx?$/,
            new TypescriptPlugin({
                excludeNames: [/.+State$/],
                excludePaths: ["node_modules/", "-app/", "test-commons/", "-build-scripts/", "test/"],
                verbose: true,
            }),
        )
        .use(".scss", new KssPlugin());

    const docs = await documentalist.documentGlobs(
        `../{${LIBRARY_AND_DOCS_PACKAGES.join(",")}}/src/**/*.mdx`,
        `../{${LIBRARY_PACKAGES.join(",")}}/src/**/*.scss`,
        `../{${LIBRARY_PACKAGES.join(",")}}/src/index.ts`,
    );

    // Post-process: replace documentalist's nav with one built from nav.json
    const navConfig = JSON.parse(readFileSync(new URL("./nav.json", import.meta.url), "utf-8"));
    applyNavConfig(docs, navConfig);

    const content = JSON.stringify(docs, transformDocumentalistData, 2);
    writeFileSync(docsDataFilePath, content);

    // Also generate a CJS module so src/index.js can re-export nav constants
    // without manually duplicating the arrays from navTypes.mts
    const navConstants = [
        `// Auto-generated by compile-docs-data.mts — do not edit`,
        `module.exports.PACKAGES = ${JSON.stringify(PACKAGES)};`,
        `module.exports.SECTIONS = ${JSON.stringify(SECTIONS)};`,
    ].join("\n");
    writeFileSync(join(generatedSrcDir, "nav-constants.js"), navConstants);
}

/**
 * @param {string} key
 * @param {any} value
 * @returns {any}
 */
function transformDocumentalistData(key, value) {
    if (typeof value === "string") {
        return interpolateClassNamespace(value);
    }

    return value;
}

/**
 * Replaces `#{$ns}` placeholder in string values  with the actual Blueprint class namespace.
 *
 * @param {string} value
 */
function interpolateClassNamespace(value: string): string {
    return value.replace(/#{\$ns}|@ns/g, Classes.getClassNamespace());
}

/**
 * Applies the nav config to documentalist output: fixes page routes and
 * replaces the nav tree.
 *
 * @param {{ pages: Record<string, any>, nav: any[] }} docs
 * @param {import("./navTypes.d.ts").NavStructure} navConfig
 */
function applyNavConfig(docs, navConfig) {
    const routeMap = buildRouteMap(navConfig);
    fixPageRoutes(docs.pages, routeMap);
    docs.nav = buildNavTree(navConfig, docs.pages, routeMap);
}

