#!/usr/bin/env node
/**
 * @license Copyright 2017 Palantir Technologies, Inc. All rights reserved.
 * @fileoverview Generates data for packages/docs-app
 */

// @ts-check

import { Documentalist, KssPlugin, MarkdownPlugin, TypescriptPlugin } from "@documentalist/compiler";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { cwd } from "node:process";
import semver from "semver";

import { Classes } from "@blueprintjs/core";

import { hooks, markedRenderer } from "./markdownRenderer.mjs";
import { assignRoutes, buildNavTree, normalizeNavConfig } from "./navHelpers.mts";
import {
    PACKAGES,
    SECTIONS,
    type DocPage,
    type NavStructure,
    type NavTreeNode,
    type RawNavStructure,
} from "./navTypes.mts";

/** Run Documentalist on Sass, TypeScript, and package.json files in these packages */
const LIBRARY_PACKAGES = ["core", "datetime", "datetime2", "icons", "select", "table", "labs"];

/** This package is expected to have the markdown "navPage" */
const DOCS_PACKAGE = "docs-app";

/** Run Documentalist on Markdown files in these packages */
const LIBRARY_AND_DOCS_PACKAGES = [...LIBRARY_PACKAGES, DOCS_PACKAGE];

console.info(`[docs-data] compiling documentation for library packages: ${LIBRARY_PACKAGES.join(", ")}`);

// assume we are running from packages/docs-app
const monorepoRootDir = resolve(cwd(), "../../");
const generatedSrcDir = resolve(cwd(), "./src/generated");
const docsDataFilePath = join(generatedSrcDir, "docs.json");

try {
    if (!existsSync(generatedSrcDir)) {
        mkdirSync(generatedSrcDir);
    }
    await generateDocumentalistData();
    await generateNpmVersions();
} catch (err) {
    console.error("[docs-data] ERROR:", err);
    process.exit(1);
}

console.info(`[docs-data] successfully generated docs.json and npm-data.json`);

async function generateDocumentalistData(): Promise<void> {
    const documentalist = new Documentalist({
        markdown: {
            hooks,
            renderer: markedRenderer,
        },
        // must mark our @Decorator APIs as reserved so we can use them in code samples
        reservedTags: ["import", "ContextMenuTarget", "HotkeysTarget", "param", "returns", "use"],
        sourceBaseDir: monorepoRootDir,
    })
        .use(".md", {
            compile: files =>
                // HACKHACK: special case for Windows environment
                // see https://github.com/palantir/documentalist/issues/98
                process.platform === "win32" ? files.map(file => file.read().replace(/\r\n/g, "\n")) : files,
        })
        // TODO: once documentalist is fully removed, stop generating nav via documentalist
        .use(".md", new MarkdownPlugin({ navPage: "_nav" }))
        .use(
            /\.tsx?$/,
            new TypescriptPlugin({
                excludeNames: [/.+State$/],
                excludePaths: ["node_modules/", "-app/", "test-commons/", "-build-scripts/", "test/"],
                verbose: true,
            }),
        )
        .use(".scss", new KssPlugin());

    const docs = await documentalist.documentGlobs(
        `../{${LIBRARY_AND_DOCS_PACKAGES.join(",")}}/src/**/*.md`,
        `../{${LIBRARY_PACKAGES.join(",")}}/src/**/*.scss`,
        `../{${LIBRARY_PACKAGES.join(",")}}/src/index.ts`,
    );

    // Post-process: replace documentalist's nav with one built from nav.json
    const navConfig = JSON.parse(readFileSync(new URL("./nav.json", import.meta.url), "utf-8"));
    applyNavConfig(docs, navConfig);

    const content = JSON.stringify(docs, transformDocumentalistData, 2);
    writeFileSync(docsDataFilePath, content);

    // Also generate a CJS module so src/index.js can re-export nav constants
    // without manually duplicating the arrays from navTypes.mts
    const navConstants = [
        `// Auto-generated by compile-docs-data.mts — do not edit`,
        `module.exports.PACKAGES = ${JSON.stringify(PACKAGES)};`,
        `module.exports.SECTIONS = ${JSON.stringify(SECTIONS)};`,
    ].join("\n");
    writeFileSync(join(generatedSrcDir, "nav-constants.js"), navConstants);
}

/**
 * @param {string} key
 * @param {any} value
 * @returns {any}
 */
function transformDocumentalistData(key, value) {
    if (typeof value === "string") {
        return interpolateClassNamespace(value);
    }

    return value;
}

/**
 * Replaces `#{$ns}` placeholder in string values  with the actual Blueprint class namespace.
 *
 * @param {string} value
 */
function interpolateClassNamespace(value: string): string {
    return value.replace(/#{\$ns}|@ns/g, Classes.getClassNamespace());
}

// ---------------------------------------------------------------------------
// Nav post-processing: build nav tree & fix routes from nav.json
// ---------------------------------------------------------------------------

/**
 * Applies the nav config to documentalist output: fixes page routes and
 * replaces the nav tree.
 *
 * @param {{ pages: Record<string, any>, nav: any[] }} docs
 * @param {Record<string, any[]>} navConfig
 */
function applyNavConfig(docs, navConfig) {
    // Step 2a: build route map
    const routeMap = buildRouteMap(navConfig);

    // Step 2b: fix routes in docs.pages
    fixPageRoutes(docs.pages, routeMap);

    // Step 2c + 2d: build nav tree and replace docs.nav
    docs.nav = buildNavTree(navConfig, docs.pages, routeMap);
}

/**
 * Walk nav config to compute the full route for every page reference.
 *
 * @param {Record<string, any[]>} navConfig
 * @returns {Map<string, string>}
 */
function buildRouteMap(navConfig) {
    /** @type {Map<string, string>} */
    const routeMap = new Map();

    /**
     * @param {string} ref
     * @param {string} parentRoute
     */
    function walk(ref, parentRoute) {
        const route = parentRoute ? `${parentRoute}/${ref}` : ref;
        routeMap.set(ref, route);
        const children = navConfig[ref];
        if (children) {
            for (const child of children) {
                if (typeof child === "string") {
                    walk(child, route);
                }
                // heading markers are skipped — they don't define pages
            }
        }
    }

    for (const ref of navConfig["_nav"]) {
        walk(ref, "");
    }

    return routeMap;
}

/**
 * Fix routes in every page and its content heading objects.
 * Without @page tags, documentalist produces empty heading routes,
 * so we reconstruct them from the page route and heading value.
 *
 * @param {Record<string, any>} pages
 * @param {Map<string, string>} routeMap
 */
function fixPageRoutes(pages, routeMap) {
    for (const [ref, page] of Object.entries(pages)) {
        const correctRoute = routeMap.get(ref);
        if (correctRoute === undefined) {
            // Page not in nav config (e.g. _nav) — leave as-is
            continue;
        }

        page.route = correctRoute;

        // Reconstruct heading routes in page.contents
        for (const item of page.contents) {
            if (typeof item === "object" && item !== null && item.tag === "heading") {
                if (item.level === 1) {
                    // Level 1 heading = page title, route is the page route
                    item.route = correctRoute;
                } else {
                    // Level 2+ headings: pageRoute.slugified-heading-value
                    item.route = correctRoute + "." + slugify(item.value);
                }
            }
        }
    }
}

/**
 * Convert a heading value to a URL-friendly slug.
 * Matches documentalist's slugification: lowercase, replace non-[a-z0-9-] with hyphens.
 *
 * @param {string} value
 * @returns {string}
 */
function slugify(value) {
    return value.toLowerCase().replace(/[^a-z0-9-]/g, "-");
}

/**
 * Build the full nav tree from nav.json and page data.
 *
 * @param {Record<string, any[]>} navConfig
 * @param {Record<string, any>} pages
 * @param {Map<string, string>} routeMap
 * @returns {any[]}
 */
function buildNavTree(navConfig, pages, routeMap) {
    return navConfig["_nav"].map(ref => buildPageNode(ref, 1, navConfig, pages, routeMap));
}

/**
 * Recursively build a PageNode for the nav tree.
 *
 * @param {string} ref
 * @param {number} level
 * @param {Record<string, any[]>} navConfig
 * @param {Record<string, any>} pages
 * @param {Map<string, string>} routeMap
 * @returns {any}
 */
function buildPageNode(ref, level, navConfig, pages, routeMap) {
    const page = pages[ref];
    const route = routeMap.get(ref);
    const navChildren = navConfig[ref] || [];
    const hasHeadingMarkers = navChildren.some(c => typeof c === "object");

    // Extract heading children from page contents (level >= 2, i.e. not the @# title)
    const headingChildren = extractHeadingChildren(page, level);

    /** @type {any[]} */
    let children;

    if (hasHeadingMarkers) {
        // Interleaved mode: walk nav.json entries in order, matching heading markers
        // against page content headings by title
        const headingsByTitle = new Map();
        for (const h of headingChildren) {
            headingsByTitle.set(h.title, h);
        }

        children = [];
        for (const entry of navChildren) {
            if (typeof entry === "string") {
                children.push(buildPageNode(entry, level + 1, navConfig, pages, routeMap));
            } else if (entry.heading) {
                const matched = headingsByTitle.get(entry.heading);
                if (matched) {
                    children.push(matched);
                }
            }
        }
    } else {
        // Default mode: headings first, then page children
        const pageChildren = navChildren
            .filter(c => typeof c === "string")
            .map(childRef => buildPageNode(childRef, level + 1, navConfig, pages, routeMap));
        children = [...headingChildren, ...pageChildren];
    }

    return {
        children,
        level,
        reference: ref,
        route,
        title: page.title,
    };
}

/**
 * Extract heading nodes from page contents for the nav tree.
 * Skips level-1 headings (the page title). Adjusts heading levels
 * relative to the page's position in the nav tree.
 *
 * @param {any} page
 * @param {number} pageNavLevel
 * @returns {any[]}
 */
function extractHeadingChildren(page, pageNavLevel) {
    const levelOffset = pageNavLevel - 1;
    /** @type {any[]} */
    const result = [];

    for (const item of page.contents) {
        if (typeof item === "object" && item !== null && item.tag === "heading" && item.level >= 2) {
            result.push({
                title: item.value,
                level: item.level + levelOffset,
                route: item.route,
            });
        }
    }

    return result;
}

// ---------------------------------------------------------------------------
// NPM version data generation
// ---------------------------------------------------------------------------

async function generateNpmVersions() {
    /** @type {Record<string, { name: string; version: string; versions: string[] }>} */
    const result = {};

    for (const pkg of LIBRARY_PACKAGES) {
        const pkgJsonPath = resolve(monorepoRootDir, "packages", pkg, "package.json");
        if (!existsSync(pkgJsonPath)) continue;

        const pkgJson = JSON.parse(readFileSync(pkgJsonPath, "utf-8"));
        const packageName = pkgJson.name;

        let versions = [pkgJson.version];
        try {
            const response = await fetch(`https://registry.npmjs.org/${packageName}`);
            if (response.ok) {
                const data = await response.json();
                const allVersions = Object.keys(data.versions);
                // keep one (latest) version per major, sorted descending
                const majors = new Map();
                for (const v of allVersions) {
                    const maj = semver.major(v);
                    if (maj === 0) continue;
                    if (!majors.has(maj) || semver.gt(v, majors.get(maj))) {
                        majors.set(maj, v);
                    }
                }
                versions = Array.from(majors.values()).sort((a, b) => semver.rcompare(a, b));
            } else {
                console.warn(`[docs-data] npm registry returned ${response.status} for ${packageName}, using local version`);
            }
        } catch (e) {
            console.warn(`[docs-data] failed to fetch npm versions for ${packageName}, using local version:`, e.message);
        }

        result[packageName] = {
            name: packageName,
            version: pkgJson.version,
            versions,
        };
    }

    writeFileSync(join(generatedSrcDir, "npm-data.json"), JSON.stringify(result, null, 2) + "\n");
    console.info("[docs-data] generated npm-data.json");
}
