#!/usr/bin/env node
/**
 * @license Copyright 2017 Palantir Technologies, Inc. All rights reserved.
 * @fileoverview Generates data for packages/docs-app
 */

import { Documentalist, KssPlugin, MarkdownPlugin, NpmPlugin, TypescriptPlugin } from "@documentalist/compiler";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { cwd } from "node:process";
import semver from "semver";

import { Classes } from "@blueprintjs/core";

import { hooks, markedRenderer } from "./markdownRenderer.mjs";
import { buildNavTree, buildRouteMap, fixPageRoutes, normalizeNavConfig } from "./navHelpers.mts";
import type { NavStructure, RawNavStructure } from "./navTypes.ts";

/** Run Documentalist on Sass, TypeScript, and package.json files in these packages */
const LIBRARY_PACKAGES = ["core", "datetime", "datetime2", "icons", "select", "table", "labs"];

/** This package is expected to have the markdown "navPage" */
const DOCS_PACKAGE = "docs-app";

/** Run Documentalist on Markdown files in these packages */
const LIBRARY_AND_DOCS_PACKAGES = [...LIBRARY_PACKAGES, DOCS_PACKAGE];

console.info(`[docs-data] compiling documentation for library packages: ${LIBRARY_PACKAGES.join(", ")}`);

// assume we are running from packages/docs-app
const monorepoRootDir = resolve(cwd(), "../../");
const generatedSrcDir = resolve(cwd(), "./src/generated");
const docsDataFilePath = join(generatedSrcDir, "docs.json");

/** Last published version for each prior major release, used for the docs version dropdown. */
const PRIOR_MAJOR_VERSIONS: Record<string, string[]> = {
    "@blueprintjs/core": ["5.19.1", "4.20.2", "3.54.0", "2.3.1", "1.40.0"],
};

try {
    if (!existsSync(generatedSrcDir)) {
        mkdirSync(generatedSrcDir);
    }
    generateNpmData();
    await generateDocumentalistData();
    await generateNpmVersions();
} catch (err) {
    // console.error messages get swallowed by lerna but console.log is emitted to terminal.
    console.error(`[docs-data] ERROR when generating JSON docs data:`);
    throw new Error(err as string);
}

console.info(`[docs-data] successfully generated docs.json and npm-data.json`);

async function generateDocumentalistData(): Promise<void> {
    const documentalist = new Documentalist({
        markdown: {
            hooks,
            renderer: markedRenderer,
        },
        // must mark our @Decorator APIs as reserved so we can use them in code samples
        reservedTags: ["import", "ContextMenuTarget", "HotkeysTarget", "param", "returns", "use"],
        sourceBaseDir: monorepoRootDir,
    })
        .use(".mdx", {
            compile: files =>
                // HACKHACK: special case for Windows environment
                // see https://github.com/palantir/documentalist/issues/98
                process.platform === "win32" ? files.map(file => file.read().replace(/\r\n/g, "\n")) : files,
        })
        .use(".mdx", new MarkdownPlugin({ navPage: "_nav" }))
        .use(
            /\.tsx?$/,
            new TypescriptPlugin({
                excludeNames: [/.+State$/],
                excludePaths: ["node_modules/", "-app/", "test-commons/", "-build-scripts/", "test/"],
                verbose: true,
            }),
        )
        .use(".scss", new KssPlugin());

    const docs = await documentalist.documentGlobs(
        `../{${LIBRARY_AND_DOCS_PACKAGES.join(",")}}/src/**/*.mdx`,
        `../{${LIBRARY_PACKAGES.join(",")}}/src/**/*.scss`,
        `../{${LIBRARY_PACKAGES.join(",")}}/src/index.ts`,
    );

    // Post-process: replace documentalist's nav with one built from nav.json
    const rawConfig: RawNavStructure = JSON.parse(readFileSync(new URL("./nav.json", import.meta.url), "utf-8"));
    const navConfig = normalizeNavConfig(rawConfig);
    applyNavConfig(docs, navConfig);

    const content = JSON.stringify(docs, transformDocumentalistData, 2);
    writeFileSync(docsDataFilePath, content);

    // Also generate a CJS module so src/index.js can re-export nav constants
    // without manually duplicating the arrays from navTypes.mts
    const navConstants = [
        `// Auto-generated by compile-docs-data.mts — do not edit`,
        `module.exports.PACKAGES = ${JSON.stringify(PACKAGES)};`,
        `module.exports.SECTIONS = ${JSON.stringify(SECTIONS)};`,
    ].join("\n");
    writeFileSync(join(generatedSrcDir, "nav-constants.js"), navConstants);
}

function transformDocumentalistData(key: string, value: any): any {
    if (key === "versions" && Array.isArray(value)) {
        // one major version per release
        const majors = new Map<number, string>();
        for (const version of value) {
            const major = semver.major(version);
            if (!majors.has(major) || semver.gt(version, majors.get(major)!)) {
                majors.set(major, version);
            }
        }
        // reverse the list so highest version is first (easier indexing)
        return Array.from(majors.values()).reverse();
    }

    if (typeof value === "string") {
        return interpolateClassNamespace(value);
    }

    return value;
}

function interpolateClassNamespace(value: string): string {
    return value.replace(/#{\$ns}|@ns/g, Classes.getClassNamespace());
}

function generateNpmData(): void {
    const npmDataFilePath = join(generatedSrcDir, "npm-data.json");
    const npmData: Record<string, { name: string; version: string; versions: string[] }> = {};
    for (const pkg of LIBRARY_PACKAGES) {
        const pkgJsonPath = join(monorepoRootDir, "packages", pkg, "package.json");
        const { name, version } = JSON.parse(readFileSync(pkgJsonPath, "utf-8"));
        npmData[name] = { name, version, versions: [version, ...(PRIOR_MAJOR_VERSIONS[name] ?? [])] };
    }
    writeFileSync(npmDataFilePath, JSON.stringify(npmData, null, 2) + "\n");
    console.info("[docs-data] successfully generated npm-data.json");
}

function applyNavConfig(docs: { pages: Record<string, any>; nav: any[] }, navConfig: NavStructure): void {
    const routeMap = buildRouteMap(navConfig);
    fixPageRoutes(docs.pages, routeMap);
    docs.nav = buildNavTree(navConfig, docs.pages, routeMap);
}
