/*
 * Copyright 2026 Palantir Technologies, Inc. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable sort-keys -- Declaration order follows the documented NHS Digital component recipes. */

import { BLUEPRINT_THEME_V1_SCHEMA_URL, type BlueprintThemeV1 } from "@blueprintjs/core";

/** NHS Digital's published light theme, expressed without author-owned Blueprint selectors. */
export const NHS_DIGITAL_THEME = {
    $schema: BLUEPRINT_THEME_V1_SCHEMA_URL,
    tokens: {
        "--bp-theme-nhs-white": "#ffffff",
        "--bp-theme-nhs-text": "#231f20",
        "--bp-theme-nhs-muted": "#3f525f",
        "--bp-theme-nhs-disabled": "#d5dade",
        "--bp-theme-nhs-disabled-background": "#edf1f1",
        "--bp-theme-nhs-disabled-foreground": "#768692",
        "--bp-theme-nhs-blue": "#005bbb",
        "--bp-theme-nhs-dark-blue": "#003087",
        "--bp-theme-nhs-green": "#006646",
        "--bp-theme-nhs-red": "#b30f0f",
        "--bp-theme-nhs-yellow": "#fae100",
        "--bp-theme-nhs-pale-grey": "#e8edee",
        "--bp-theme-nhs-pale-grey-tint": "#f6f8f8",
        "--bp-theme-nhs-focus-ring": "0.1875rem",
        "--bp-theme-nhs-input-border": "0.0625rem",

        "--bp-intent-primary-rest": "var(--bp-theme-nhs-blue)",
        "--bp-intent-primary-hover": "var(--bp-theme-nhs-dark-blue)",
        "--bp-intent-primary-active": "var(--bp-theme-nhs-blue)",
        "--bp-intent-primary-foreground": "var(--bp-theme-nhs-white)",
        "--bp-intent-success-rest": "var(--bp-theme-nhs-green)",
        "--bp-intent-success-hover": "var(--bp-theme-nhs-green)",
        "--bp-intent-success-active": "var(--bp-theme-nhs-green)",
        "--bp-intent-success-foreground": "var(--bp-theme-nhs-white)",
        // NHS Digital has no warning Button, so BP7's accessible warning tokens remain unchanged.
        "--bp-intent-danger-rest": "var(--bp-theme-nhs-red)",
        "--bp-intent-danger-hover": "var(--bp-theme-nhs-red)",
        "--bp-intent-danger-active": "var(--bp-theme-nhs-red)",
        "--bp-intent-danger-foreground": "var(--bp-theme-nhs-white)",

        "--bp-surface-background-color-base-rest": "var(--bp-theme-nhs-white)",
        "--bp-surface-border-color-neutral": "var(--bp-theme-nhs-disabled)",
        "--bp-surface-border-color-primary": "var(--bp-theme-nhs-blue)",
        "--bp-surface-border-color-success": "var(--bp-theme-nhs-green)",
        "--bp-surface-border-color-danger": "var(--bp-theme-nhs-red)",
        "--bp-surface-divider-color-default": "var(--bp-theme-nhs-pale-grey)",
        "--bp-surface-layer-color-neutral-hover": "color-mix(in srgb, var(--bp-theme-nhs-muted) 6%, transparent)",
        "--bp-surface-layer-color-neutral-active": "color-mix(in srgb, var(--bp-theme-nhs-muted) 12%, transparent)",
        "--bp-surface-layer-color-primary-hover": "color-mix(in srgb, var(--bp-theme-nhs-dark-blue) 6%, transparent)",
        "--bp-surface-layer-color-primary-active": "color-mix(in srgb, var(--bp-theme-nhs-blue) 12%, transparent)",
        "--bp-surface-layer-color-success-hover": "color-mix(in srgb, var(--bp-theme-nhs-green) 6%, transparent)",
        "--bp-surface-layer-color-success-active": "color-mix(in srgb, var(--bp-theme-nhs-green) 12%, transparent)",
        "--bp-surface-layer-color-danger-hover": "color-mix(in srgb, var(--bp-theme-nhs-red) 6%, transparent)",
        "--bp-surface-layer-color-danger-active": "color-mix(in srgb, var(--bp-theme-nhs-red) 12%, transparent)",
        "--bp-surface-shadow-3": "0.125rem 0.375rem 0.75rem oklch(0% 0 0deg / 10%)",
        "--bp-emphasis-transition-duration": "150ms",
        "--bp-emphasis-focus-color": "var(--bp-theme-nhs-yellow)",
        "--bp-emphasis-focus-width": "var(--bp-theme-nhs-focus-ring)",
        "--bp-emphasis-focus-offset": "0",

        "--bp-typography-family-body": '"Frutiger W01", Arial, sans-serif',
        "--bp-typography-family-heading": "var(--bp-typography-family-body)",
        "--bp-typography-family-display": "var(--bp-typography-family-body)",
        "--bp-typography-heading-margin-block-start": "0",
        "--bp-typography-heading-margin-block-end": "1.25rem",
        "--bp-typography-heading-h1-font-size": "3rem",
        "--bp-typography-heading-h1-line-height": "1.2",
        "--bp-typography-heading-h1-letter-spacing": "-0.125rem",
        "--bp-typography-heading-h2-font-size": "2.25rem",
        "--bp-typography-heading-h2-line-height": "1.1667",
        "--bp-typography-heading-h2-letter-spacing": "-0.063rem",
        "--bp-typography-heading-h3-font-size": "1.875rem",
        "--bp-typography-heading-h3-line-height": "1.20048",
        "--bp-typography-heading-h3-letter-spacing": "-0.063rem",
        "--bp-typography-heading-h4-font-size": "1.625rem",
        "--bp-typography-heading-h4-line-height": "1.19267",
        "--bp-typography-heading-h4-letter-spacing": "-0.0277rem",
        "--bp-typography-heading-h5-font-size": "1.375rem",
        "--bp-typography-heading-h5-line-height": "1.3125",
        "--bp-typography-heading-h5-letter-spacing": "-0.0277rem",
        "--bp-typography-heading-h6-font-size": "1.125rem",
        "--bp-typography-heading-h6-line-height": "1.3125",
        "--bp-typography-heading-h6-letter-spacing": "-0.0277rem",
        "--bp-typography-size-sm": "1rem",
        "--bp-typography-size-md": "1.125rem",
        "--bp-typography-weight-default": "400",
        "--bp-typography-weight-strong": "600",
        "--bp-typography-line-height-running-factor": "1.6",
        "--bp-typography-color-base": "var(--bp-theme-nhs-text)",
        "--bp-typography-color-muted": "var(--bp-theme-nhs-muted)",
        "--bp-typography-color-disabled": "var(--bp-theme-nhs-disabled-foreground)",
        "--bp-typography-color-intent-primary": "var(--bp-theme-nhs-blue)",
        "--bp-typography-color-intent-success": "var(--bp-theme-nhs-green)",
        "--bp-typography-color-intent-danger": "var(--bp-theme-nhs-red)",

        "--bp-button-min-block-size": "2.75rem",
        "--bp-button-padding-block": "0.625rem",
        "--bp-button-padding-inline": "1.25rem",
        "--bp-button-border-radius": "9999px",
        "--bp-button-border-width-solid": "0.125rem",
        "--bp-button-border-width-outlined": "0.125rem",
        "--bp-button-font-family": "var(--bp-typography-family-body)",
        "--bp-button-font-size": "0.875rem",
        "--bp-button-font-weight": "600",
        "--bp-button-line-height": "1.25rem",
        "--bp-button-background-default-rest": "var(--bp-theme-nhs-blue)",
        "--bp-button-background-default-hover": "var(--bp-theme-nhs-dark-blue)",
        "--bp-button-background-default-active": "var(--bp-theme-nhs-blue)",
        "--bp-button-background-default-disabled": "var(--bp-theme-nhs-disabled)",
        "--bp-button-background-default-active-disabled": "var(--bp-theme-nhs-disabled)",
        "--bp-button-background-intent-primary-rest": "var(--bp-theme-nhs-blue)",
        "--bp-button-background-intent-primary-hover": "var(--bp-theme-nhs-dark-blue)",
        "--bp-button-background-intent-primary-active": "var(--bp-theme-nhs-blue)",
        "--bp-button-background-intent-primary-disabled": "var(--bp-theme-nhs-disabled)",
        "--bp-button-background-intent-success-rest": "var(--bp-theme-nhs-green)",
        "--bp-button-background-intent-success-hover": "var(--bp-theme-nhs-green)",
        "--bp-button-background-intent-success-active": "var(--bp-theme-nhs-green)",
        "--bp-button-background-intent-success-disabled": "var(--bp-theme-nhs-disabled)",
        "--bp-button-background-intent-danger-rest": "var(--bp-theme-nhs-red)",
        "--bp-button-background-intent-danger-hover": "var(--bp-theme-nhs-red)",
        "--bp-button-background-intent-danger-active": "var(--bp-theme-nhs-red)",
        "--bp-button-background-intent-danger-disabled": "var(--bp-theme-nhs-disabled)",
        "--bp-button-foreground-default-rest": "var(--bp-theme-nhs-white)",
        "--bp-button-foreground-default-disabled": "var(--bp-theme-nhs-muted)",
        "--bp-button-foreground-intent-primary-rest": "var(--bp-theme-nhs-white)",
        "--bp-button-foreground-intent-primary-disabled": "var(--bp-theme-nhs-muted)",
        "--bp-button-foreground-intent-success-rest": "var(--bp-theme-nhs-white)",
        "--bp-button-foreground-intent-success-disabled": "var(--bp-theme-nhs-muted)",
        "--bp-button-foreground-intent-danger-rest": "var(--bp-theme-nhs-white)",
        "--bp-button-foreground-intent-danger-disabled": "var(--bp-theme-nhs-muted)",
        "--bp-button-icon-foreground-default-rest": "var(--bp-theme-nhs-white)",
        "--bp-button-foreground-minimal-intent-default-rest": "var(--bp-theme-nhs-blue)",
        "--bp-button-foreground-minimal-intent-default-hover": "var(--bp-theme-nhs-dark-blue)",
        "--bp-button-foreground-minimal-intent-default-active": "var(--bp-theme-nhs-blue)",
        "--bp-button-foreground-minimal-intent-primary-rest": "var(--bp-theme-nhs-blue)",
        "--bp-button-foreground-minimal-intent-primary-hover": "var(--bp-theme-nhs-dark-blue)",
        "--bp-button-foreground-minimal-intent-primary-active": "var(--bp-theme-nhs-blue)",
        "--bp-button-foreground-minimal-intent-success-rest": "var(--bp-theme-nhs-green)",
        "--bp-button-foreground-minimal-intent-success-hover": "var(--bp-theme-nhs-green)",
        "--bp-button-foreground-minimal-intent-success-active": "var(--bp-theme-nhs-green)",
        "--bp-button-foreground-minimal-intent-danger-rest": "var(--bp-theme-nhs-red)",
        "--bp-button-foreground-minimal-intent-danger-hover": "var(--bp-theme-nhs-red)",
        "--bp-button-foreground-minimal-intent-danger-active": "var(--bp-theme-nhs-red)",
        "--bp-button-shadow-rest": "none",
        "--bp-button-shadow-active": "none",

        "--bp-input-background-rest": "var(--bp-theme-nhs-white)",
        "--bp-input-background-disabled": "var(--bp-theme-nhs-disabled-background)",
        "--bp-input-foreground-rest": "var(--bp-theme-nhs-text)",
        "--bp-input-foreground-disabled": "var(--bp-theme-nhs-muted)",
        "--bp-input-foreground-placeholder": "var(--bp-theme-nhs-muted)",
        "--bp-input-shadow-rest": "inset 0 0 0 0.0625rem var(--bp-theme-nhs-text)",
        "--bp-input-shadow-focus":
            "0 0 0 var(--bp-theme-nhs-focus-ring) var(--bp-theme-nhs-yellow), inset 0 0 0 var(--bp-theme-nhs-input-border) var(--bp-theme-nhs-text)",
        "--bp-input-shadow-readonly": "inset 0 0 0 var(--bp-theme-nhs-input-border) var(--bp-theme-nhs-text)",
        "--bp-input-shadow-intent-primary-rest":
            "inset 0 0 0 var(--bp-theme-nhs-input-border) var(--bp-theme-nhs-blue)",
        "--bp-input-shadow-intent-primary-focus":
            "0 0 0 var(--bp-theme-nhs-focus-ring) var(--bp-theme-nhs-yellow), inset 0 0 0 var(--bp-theme-nhs-input-border) var(--bp-theme-nhs-blue)",
        "--bp-input-shadow-intent-primary-readonly":
            "inset 0 0 0 var(--bp-theme-nhs-input-border) var(--bp-theme-nhs-blue)",
        "--bp-input-shadow-intent-success-rest":
            "inset 0 0 0 var(--bp-theme-nhs-input-border) var(--bp-theme-nhs-green)",
        "--bp-input-shadow-intent-success-focus":
            "0 0 0 var(--bp-theme-nhs-focus-ring) var(--bp-theme-nhs-yellow), inset 0 0 0 var(--bp-theme-nhs-input-border) var(--bp-theme-nhs-green)",
        "--bp-input-shadow-intent-success-readonly":
            "inset 0 0 0 var(--bp-theme-nhs-input-border) var(--bp-theme-nhs-green)",
        "--bp-input-shadow-intent-danger-rest": "inset 0 0 0 var(--bp-theme-nhs-input-border) var(--bp-theme-nhs-red)",
        "--bp-input-shadow-intent-danger-focus":
            "0 0 0 var(--bp-theme-nhs-focus-ring) var(--bp-theme-nhs-yellow), inset 0 0 0 var(--bp-theme-nhs-input-border) var(--bp-theme-nhs-red)",
        "--bp-input-shadow-intent-danger-readonly":
            "inset 0 0 0 var(--bp-theme-nhs-input-border) var(--bp-theme-nhs-red)",

        "--bp-menu-background-rest": "var(--bp-theme-nhs-white)",
        "--bp-menu-foreground-rest": "var(--bp-theme-nhs-text)",
        "--bp-menu-foreground-muted": "var(--bp-theme-nhs-muted)",
        "--bp-menu-foreground-disabled": "var(--bp-theme-nhs-disabled-foreground)",
        "--bp-menu-border-radius": "0.375rem",
        "--bp-menu-font-family": "var(--bp-typography-family-body)",
        "--bp-menu-font-size": "1.125rem",
        "--bp-menu-divider-color": "var(--bp-theme-nhs-pale-grey)",
        "--bp-menu-item-border-radius": "0",
        "--bp-menu-item-background-hover": "var(--bp-theme-nhs-blue)",
        "--bp-menu-item-background-active": "var(--bp-theme-nhs-blue)",
        "--bp-menu-item-background-intent-primary-hover": "var(--bp-theme-nhs-dark-blue)",
        "--bp-menu-item-background-intent-primary-active": "var(--bp-theme-nhs-blue)",
        "--bp-menu-item-background-intent-success-hover": "var(--bp-theme-nhs-green)",
        "--bp-menu-item-background-intent-success-active": "var(--bp-theme-nhs-green)",
        "--bp-menu-item-background-intent-danger-hover": "var(--bp-theme-nhs-red)",
        "--bp-menu-item-background-intent-danger-active": "var(--bp-theme-nhs-red)",
        "--bp-menu-item-foreground-intent-primary": "var(--bp-theme-nhs-white)",
        "--bp-menu-item-foreground-intent-success": "var(--bp-theme-nhs-white)",
        "--bp-menu-item-foreground-intent-danger": "var(--bp-theme-nhs-white)",

        "--bp-popover-background-rest": "var(--bp-theme-nhs-white)",
        "--bp-popover-foreground-rest": "var(--bp-theme-nhs-text)",
        "--bp-popover-shadow": "0.125rem 0.375rem 0.75rem oklch(0% 0 0deg / 10%)",
        "--bp-popover-border-radius": "0.375rem",
        "--bp-popover-font-family": "var(--bp-typography-family-body)",
        "--bp-popover-font-size": "1.125rem",
        "--bp-popover-arrow-shadow": "1px 1px 6px oklch(0% 0 0deg / 20%)",
        "--bp-popover-arrow-border-opacity": "10%",
    },
    components: {
        button: {
            base: {
                backgroundImage: "none",
                borderStyle: "solid",
                boxShadow: "0 0 0 var(--bp-theme-nhs-focus-ring) transparent",
                outline: "0",
                transform: "none",
                transitionDuration: "150ms",
                transitionProperty: "background-color, border-color, box-shadow",
                ":hover": {
                    boxShadow: "0 0 0 var(--bp-theme-nhs-focus-ring) var(--bp-theme-nhs-yellow)",
                },
                ":focus": {
                    boxShadow: "0 0 0 var(--bp-theme-nhs-focus-ring) var(--bp-theme-nhs-yellow)",
                },
                ":active": {
                    boxShadow: "0 0 0 var(--bp-theme-nhs-focus-ring) transparent",
                    transform: "translateY(0.125rem)",
                    transitionProperty: "none",
                },
            },
            active: {
                boxShadow: "0 0 0 var(--bp-theme-nhs-focus-ring) transparent",
                transform: "translateY(0.125rem)",
                transitionProperty: "none",
            },
            // These Blueprint variants provide the documented NHS component-specific mappings in this demo.
            outlined: {
                backgroundColor: "var(--bp-theme-nhs-white)",
                borderColor: "var(--bp-theme-nhs-blue)",
                color: "var(--bp-theme-nhs-blue)",
                ":hover": {
                    backgroundColor: "var(--bp-theme-nhs-white)",
                    borderColor: "var(--bp-theme-nhs-text)",
                    color: "var(--bp-theme-nhs-blue)",
                },
                ":focus": {
                    backgroundColor: "var(--bp-theme-nhs-white)",
                    borderColor: "var(--bp-theme-nhs-text)",
                    color: "var(--bp-theme-nhs-blue)",
                },
                ":active": {
                    backgroundColor: "var(--bp-theme-nhs-white)",
                    borderColor: "var(--bp-theme-nhs-blue)",
                    color: "var(--bp-theme-nhs-blue)",
                },
            },
            minimal: {
                backgroundColor: "var(--bp-theme-nhs-white)",
                borderColor: "var(--bp-theme-nhs-white)",
                borderStyle: "solid",
                borderWidth: "0.125rem",
                color: "var(--bp-theme-nhs-blue)",
            },
            "intent:success": {
                backgroundColor: "var(--bp-theme-nhs-green)",
                borderColor: "var(--bp-theme-nhs-green)",
                color: "var(--bp-theme-nhs-white)",
            },
            "intent:danger": {
                backgroundColor: "var(--bp-theme-nhs-red)",
                borderColor: "var(--bp-theme-nhs-red)",
                color: "var(--bp-theme-nhs-white)",
            },
            disabled: {
                backgroundColor: "var(--bp-theme-nhs-disabled)",
                backgroundImage: "none",
                borderColor: "var(--bp-theme-nhs-disabled)",
                boxShadow: "none",
                color: "var(--bp-theme-nhs-muted)",
                cursor: "not-allowed",
                opacity: "1",
                transform: "none",
            },
        },
        "button-text": {
            base: {
                boxSizing: "border-box",
                display: "block",
                lineHeight: "1.1875rem",
                minBlockSize: "1.25rem",
                overflow: "hidden",
                paddingBlockStart: "0.0625rem",
                textOverflow: "ellipsis",
                whiteSpace: "nowrap",
            },
        },
        input: {
            base: {
                backgroundImage: "none",
                blockSize: "4rem",
                borderRadius: "0.375rem",
                boxSizing: "border-box",
                fontFamily: "var(--bp-typography-family-body)",
                fontSize: "1.125rem",
                fontWeight: "400",
                lineHeight: "normal",
                paddingBlock: "1.25rem",
                paddingInline: "1.25rem",
                transitionDuration: "150ms",
                transitionProperty: "background-color, border-color, box-shadow",
                ":focus": { boxShadow: "var(--bp-input-shadow-focus)" },
            },
            active: { boxShadow: "var(--bp-input-shadow-focus)" },
            "intent:danger": {
                color: "var(--bp-theme-nhs-red)",
            },
            disabled: {
                cursor: "not-allowed",
                opacity: "1",
            },
        },
        "input-with-left-element": {
            base: { paddingInlineStart: "3.125rem" },
        },
        "input-with-action": {
            base: { paddingInlineEnd: "3.875rem" },
        },
        "input-placeholder": {
            base: { color: "var(--bp-theme-nhs-muted)", opacity: "1" },
            disabled: { color: "var(--bp-theme-nhs-disabled-foreground)" },
        },
        "input-left-icon": {
            base: {
                color: "var(--bp-theme-nhs-muted)",
                insetInlineStart: "1.25rem",
            },
        },
        "input-action": {
            base: {
                alignItems: "center",
                blockSize: "4rem",
                display: "flex",
                insetInlineEnd: "0.9375rem",
            },
        },
        "input-action-button": {
            minimal: {
                backgroundColor: "transparent",
                backgroundImage: "none",
                blockSize: "2rem",
                borderColor: "transparent",
                borderRadius: "50%",
                borderStyle: "solid",
                borderWidth: "0.0625rem",
                boxShadow: "0 0 0 var(--bp-theme-nhs-focus-ring) transparent",
                color: "var(--bp-theme-nhs-text)",
                inlineSize: "2rem",
                margin: "0",
                minBlockSize: "2rem",
                minInlineSize: "2rem",
                padding: "0.3125rem",
                ":hover": {
                    backgroundColor: "var(--bp-theme-nhs-dark-blue)",
                    borderColor: "var(--bp-theme-nhs-dark-blue)",
                    boxShadow: "0 0 0 var(--bp-theme-nhs-focus-ring) var(--bp-theme-nhs-yellow)",
                    color: "var(--bp-theme-nhs-white)",
                },
                ":focus": {
                    backgroundColor: "var(--bp-theme-nhs-dark-blue)",
                    borderColor: "var(--bp-theme-nhs-dark-blue)",
                    boxShadow: "0 0 0 var(--bp-theme-nhs-focus-ring) var(--bp-theme-nhs-yellow)",
                    color: "var(--bp-theme-nhs-white)",
                },
                ":active": {
                    backgroundColor: "transparent",
                    borderColor: "transparent",
                    boxShadow: "0 0 0 var(--bp-theme-nhs-focus-ring) transparent",
                    color: "var(--bp-theme-nhs-text)",
                    transform: "translateY(0.125rem)",
                },
            },
        },
        popover: {
            base: {
                borderRadius: "0.375rem",
                boxShadow: "var(--bp-popover-shadow)",
                minInlineSize: "31.25rem",
            },
        },
        "popover-content": {
            base: {
                backgroundColor: "var(--bp-theme-nhs-white)",
                borderColor: "var(--bp-theme-nhs-pale-grey)",
                borderRadius: "0.375rem",
                borderStyle: "solid",
                borderWidth: "0.0625rem",
                overflow: "hidden",
            },
        },
        "popover-arrow": {
            base: { display: "none" },
        },
        menu: {
            base: {
                backgroundColor: "transparent",
                borderRadius: "0",
                color: "var(--bp-theme-nhs-text)",
                fontFamily: "var(--bp-typography-family-body)",
                fontSize: "1.125rem",
                lineHeight: "1.8rem",
                minInlineSize: "0",
                paddingBlock: "0.625rem",
                paddingInline: "0",
            },
        },
        "menu-item": {
            base: {
                backgroundColor: "transparent",
                borderRadius: "0",
                boxSizing: "border-box",
                color: "var(--bp-theme-nhs-text)",
                fontFamily: "var(--bp-typography-family-body)",
                fontSize: "1.125rem",
                fontWeight: "400",
                lineHeight: "1.5rem",
                minBlockSize: "2.75rem",
                paddingBlock: "0.625rem",
                paddingInline: "1.25rem",
                transitionDuration: "150ms",
                transitionProperty: "background-color, color",
                ":hover": {
                    backgroundColor: "var(--bp-theme-nhs-blue)",
                    color: "var(--bp-theme-nhs-white)",
                },
                ":focus": {
                    backgroundColor: "var(--bp-theme-nhs-blue)",
                    color: "var(--bp-theme-nhs-white)",
                },
            },
            active: {
                backgroundColor: "var(--bp-theme-nhs-blue)",
                color: "var(--bp-theme-nhs-white)",
            },
            disabled: {
                backgroundColor: "transparent",
                color: "var(--bp-theme-nhs-disabled-foreground)",
                opacity: "1",
            },
        },
        "menu-item-icon": {
            base: { color: "inherit" },
        },
        "menu-item-label": {
            base: { color: "inherit" },
        },
        "menu-divider": {
            base: { display: "none" },
        },
        "menu-item-separator": {
            base: {
                borderBlockStart: "0.0625rem solid var(--bp-theme-nhs-pale-grey-tint)",
            },
        },
    },
} satisfies BlueprintThemeV1;
