policy:
  approval:
    - or:
      - repo owner approval
      - repo owner co-approval
      - excavator only touched baseline, gradle files or versions.props
      - excavator only touched package.json and lock files
  disapproval:
    requires:
      organizations: [ "palantir" ]

approval_rules:
  - name: repo owner approval
    requires:
      count: 1
      admins: true

  # Require two *contributing* maintainers to approve changes
  - name: repo owner co-approval
    options:
      allow_contributor: true
    requires:
      count: 2
      admins: true

  - name: excavator only touched baseline, gradle files or versions.props
    requires:
      count: 0
    if:
      has_author_in:
        users: [ "svc-excavator-bot" ]
      only_changed_files:
        paths:
          - "^\\.baseline/.*$"
          - "^.*gradle$"
          - "^gradle/wrapper/.*"
          - "^gradlew$"
          - "^gradlew.bat$"
          - "^gradle.properties$"
          - "^settings.gradle$"
          - "^versions.props$"
          - "^versions.lock$"

  - name: excavator only touched package.json and lock files
    requires:
      count: 0
    if:
      has_author_in:
        users: [ "svc-excavator-bot" ]
      only_changed_files:
        paths:
          - "^.*yarn.lock$"
          - "^.*package.json$"
