logFilters:
  - level: discard
    pattern: doesn't provide webpack
  - level: discard
    pattern: doesn't provide tslint
  - level: discard
    pattern: "fork-ts-checker-webpack-plugin is listed by your project with version 9.0.*, which doesn't satisfy what fork-ts-checker-notifier-webpack-plugin"
  - level: discard
    pattern: "webpack is listed by your project with version 5.*.*, which doesn't satisfy what istanbul-instrumenter-loader"

nodeLinker: node-modules
