# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - long-lived
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions. You may use the 'long-lived' label to mark issues
  which should never be considered stale.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been stale for one week and will now be closed to reduce
  clutter in the repo. Feel free to leave a comment if you believe it should
  be revisited, or open a fresh issue.
