/**
 * Copyright 2017 Palantir Technologies, Inc. All rights reserved.
 */

// TODO: delete this import once @documentalist/client dependency is fully removed
import { NpmPluginData, MarkdownPluginData, KssPluginData, TypescriptPluginData } from "@documentalist/client";

export type DocsCompleteData = MarkdownPluginData & NpmPluginData & KssPluginData & TypescriptPluginData;

export const docsData: DocsCompleteData;

export interface NpmPackageInfo {
    name: string;
    version: string;
    versions: string[];
}

export type NpmData = Record<string, NpmPackageInfo>;

export const npmData: NpmData;

// Minimal types replacing "@documentalist/client"

export interface HeadingNode {
    route: string;
    level: number;
    title: string;
}

export interface PageNode extends HeadingNode {
    children: Array<PageNode | HeadingNode>;
    reference: string;
}

// Props registry types (generated by react-docgen-typescript)

export interface PropInfo {
    name: string;
    required: boolean;
    type: string;
    defaultValue: string | null;
    description: string;
    deprecated: boolean | string;
    internal: boolean;
    parentName: string | null;
}

export interface PropsInfo {
    name: string;
    description: string;
    filePath: string;
    props: PropInfo[];
}

export type PropsRegistry = Record<string, PropsInfo>;

export const propsRegistry: PropsRegistry;
