/**
 * Copyright 2017 Palantir Technologies, Inc. All rights reserved.
 */

export interface NpmPackageInfo {
    name: string;
    version: string;
    versions: string[];
}

export type NpmData = Record<string, NpmPackageInfo>;

export const npmData: NpmData;

// Minimal types replacing "@documentalist/client"

export interface HeadingNode {
    route: string;
    level: number;
    title: string;
}

export interface PageNode extends HeadingNode {
    children: Array<PageNode | HeadingNode>;
    reference: string;
}

// Props registry types (generated by react-docgen-typescript)

export interface PropInfo {
    name: string;
    required: boolean;
    type: string;
    defaultValue: string | null;
    description: string;
    deprecated: boolean | string;
    internal: boolean;
    parentName: string | null;
}

export interface PropsInfo {
    name: string;
    description: string;
    filePath: string;
    props: PropInfo[];
}

export type PropsRegistry = Record<string, PropsInfo>;

export const propsRegistry: PropsRegistry;

// Page registry types (generated by compile-docs-data.mjs)

export interface PageRegistryEntry {
    component: import("react").LazyExoticComponent<import("react").ComponentType>;
    title: string;
    route: string;
    sourcePath: string;
    metadata: Record<string, unknown>;
    headings: Array<{ title: string; slug: string; level: number }>;
}

export const pageRegistry: Record<string, PageRegistryEntry>;

// Assembled docs data (replaces docs.json)

export interface DocsCompleteData {
    nav: Array<PageNode | HeadingNode>;
    pages: Record<string, PageRegistryEntry>;
    npm?: Record<string, NpmPackageInfo>;
}

export const docsData: DocsCompleteData;

export { PACKAGES, SECTIONS } from "../navTypes.mts";
export type { Package, Section } from "../navTypes.mts";
