/*
 * Copyright 2026 Palantir Technologies, Inc. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { ComponentType, LazyExoticComponent } from "react";

export interface PageRegistryEntry {
    component: LazyExoticComponent<ComponentType>;
    title: string;
    route: string;
    sourcePath: string;
    metadata: Record<string, unknown>;
    headings: Array<{ title: string; slug: string; level: number }>;
}

export interface HeadingNode {
    route: string;
    level: number;
    title: string;
}

export interface PageNode extends HeadingNode {
    children: Array<PageNode | HeadingNode>;
    reference: string;
}

export function isPageNode(node: PageNode | HeadingNode): node is PageNode {
    return "children" in node && "reference" in node;
}

export interface NpmPackageInfo {
    name: string;
    version: string;
    versions: string[];
}

export type NpmData = Record<string, NpmPackageInfo>;

// ---------------------------------------------------------------------------
// Props registry types (generated by react-docgen-typescript)
// ---------------------------------------------------------------------------

/** Description of a single prop on an interface. */
export interface PropInfo {
    name: string;
    required: boolean;
    /** Flattened type string, e.g. "boolean", "Intent | undefined". */
    type: string;
    /** Default value as a string, or null if none. */
    defaultValue: string | null;
    /** JSDoc description (may contain markdown). */
    description: string;
    /** If true or a string, the prop is deprecated. String value is the deprecation message. */
    deprecated: boolean | string;
    /** If true, the prop is marked @internal and should be hidden at render time. */
    internal: boolean;
    /** Name of the parent interface this prop was declared in (for inheritance tracking). */
    parentName: string | null;
}

/** Description of a single interface / props object. */
export interface PropsInfo {
    /** The interface name (e.g. "CalloutProps"). */
    name: string;
    /** JSDoc description of the interface, if any. */
    description: string;
    /** File path where this interface is defined (relative to monorepo root). */
    filePath: string;
    /** Sorted array of props. */
    props: PropInfo[];
}

/** Registry mapping interface names to their PropsInfo. */
export type PropsRegistry = Record<string, PropsInfo>;
