/* !
 * (c) Copyright 2025 Palantir Technologies Inc. All rights reserved.
 */

/**
 * Prop-type definitions for the <Box> component.
 *
 * The guiding idea behind <Box> is to provide a small, typed subset of the
 * CSS box-model and flexbox APIs as *props* instead of requiring consumers to
 * write custom styles or class names. We purposefully whitelist only a finite
 * number of safe values (see the union literals below) so that:
 *
 * 1. Design-system-approved spacing / sizing tokens can be enforced at compile
 *    time.
 * 2. We can consistently translate prop values into utility class names
 *    generated by `buildStyles`.
 * 3. Invalid HTML attributes (e.g. `foo="bar"`) are rejected by TypeScript in
 *    user code, while *supported* DOM props such as `id`, `title`, etc. are
 *    still allowed through the generic overlay.
 */

import type * as React from "react";

export type As = React.ElementType;

/**
 * The range of values for spacing tokens.
 */
type SpacingRange = 0 | 0.5 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

/**
 * The range of values for size as a percentage.
 */
type SizeRange = 25 | 50 | 75 | 100;

/**
 * The range of values for `gap`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/gap
 */
export type Gap = SpacingRange | `${SpacingRange}`;

/**
 * The range of values for `margin`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/margin
 */
export type Margin = SpacingRange | `${SpacingRange}` | "auto";

/**
 * The range of values for `padding`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/padding
 */
export type Padding = SpacingRange | `${SpacingRange}`;

/**
 * The range of values for `inset`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/inset
 */
export type Inset = SpacingRange | `${SpacingRange}`;

/**
 * The range of values for `width`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/width
 */
export type Width = SizeRange | `${SizeRange}` | "auto";

/**
 * The range of values for `height`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/height
 */
export type Height = SizeRange | `${SizeRange}` | "auto";

/**
 * The range of values for `align-content`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/align-content
 */
export type AlignContent =
    | "start"
    | "end"
    | "center"
    | "between"
    | "around"
    | "evenly"
    | "normal"
    | "baseline"
    | "stretch";

/**
 * The range of values for `align-items`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/align-items
 */
export type AlignItems = "start" | "end" | "center" | "baseline" | "stretch";

/**
 * The range of values for `align-self`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/align-self
 */
export type AlignSelf = "auto" | "start" | "end" | "center" | "baseline" | "stretch";

/**
 * The range of values for `display`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/display
 */
export type Display =
    | "block"
    | "inline-block"
    | "inline"
    | "flex"
    | "inline-flex"
    | "grid"
    | "inline-grid"
    | "table"
    | "inline-table"
    | "table-cell"
    | "table-row"
    | "none";

/**
 * The range of values for `flex`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/flex
 */
export type Flex = 1 | "1" | "auto" | "initial" | "none";

/**
 * The range of values for `flex-direction`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction
 */
export type FlexDirection = "row" | "row-reverse" | "column" | "column-reverse";

/**
 * The range of values for `flex-wrap`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap
 */
export type FlexWrap = "nowrap" | "wrap" | "wrap-reverse";

/**
 * The range of values for `justify-content`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content
 */
export type JustifyContent = "start" | "end" | "center" | "between" | "around" | "evenly" | "normal" | "stretch";

/**
 * The range of values for `justify-items`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/justify-items
 */
export type JustifyItems = "start" | "end" | "center" | "stretch";

/**
 * The range of values for `justify-self`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self
 */
export type JustifySelf = "auto" | "start" | "end" | "center" | "stretch";

/**
 * The range of values for `overflow`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/overflow
 */
export type Overflow = "visible" | "hidden" | "scroll" | "auto";

/**
 * The range of values for `position`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/position
 */
export type Position = "static" | "absolute" | "relative" | "fixed" | "sticky";

type BoxOwnProps = Readonly<{
    /**
     * Underlying element or component to render. Accepts any intrinsic
     * element name (e.g. "div", "span") or a React component.
     *
     * Defaults to "div" when omitted.
     */
    as?: As;

    /**
     * When true, `<Box>` will **not** render an extra wrapper. Instead, it will
     * clone & enhance its single child element, merging class names and props.
     */
    asChild?: boolean;

    /** Shorthand for the CSS `gap` property (applies to flex and grid layouts). */
    gap?: Gap;

    /** React children to be rendered inside the component. */
    children?: React.ReactNode;

    /** Additional class names to apply *before* Blueprint classes. */
    className?: string;

    /** Inline styles to apply directly to the root element. */
    style?: React.CSSProperties;

    // ────────────────────────────────────────────────────────────
    // Margin (logical )
    // ────────────────────────────────────────────────────────────

    /** CSS `margin` */
    margin?: Margin;
    /** CSS `margin-inline` */
    marginInline?: Margin;
    /** CSS `margin-inline-start` */
    marginInlineStart?: Margin;
    /** CSS `margin-inline-end` */
    marginInlineEnd?: Margin;
    /** CSS `margin-block` */
    marginBlock?: Margin;
    /** CSS `margin-block-start` */
    marginBlockStart?: Margin;
    /** CSS `margin-block-end` */
    marginBlockEnd?: Margin;

    // ────────────────────────────────────────────────────────────
    // Padding
    // ────────────────────────────────────────────────────────────

    /** CSS `padding` */
    padding?: Padding;
    /** CSS `padding-inline` */
    paddingInline?: Padding;
    /** CSS `padding-inline-start` */
    paddingInlineStart?: Padding;
    /** CSS `padding-inline-end` */
    paddingInlineEnd?: Padding;
    /** CSS `padding-block` */
    paddingBlock?: Padding;
    /** CSS `padding-block-start` */
    paddingBlockStart?: Padding;
    /** CSS `padding-block-end` */
    paddingBlockEnd?: Padding;

    // ────────────────────────────────────────────────────────────
    // Inset
    // ────────────────────────────────────────────────────────────

    /** CSS `inset` */
    inset?: Inset;
    /** CSS `inset-inline` */
    insetInline?: Inset;
    /** CSS `inset-inline-start` */
    insetInlineStart?: Inset;
    /** CSS `inset-inline-end` */
    insetInlineEnd?: Inset;
    /** CSS `inset-block` */
    insetBlock?: Inset;
    /** CSS `inset-block-start` */
    insetBlockStart?: Inset;
    /** CSS `inset-block-end` */
    insetBlockEnd?: Inset;

    // ────────────────────────────────────────────────────────────
    // Size
    // ────────────────────────────────────────────────────────────

    /** CSS `width` */
    width?: Width;
    /** CSS `height` */
    height?: Height;

    // ────────────────────────────────────────────────────────────
    // Flexbox & Grid alignment
    // ────────────────────────────────────────────────────────────

    /** CSS `align-content` */
    alignContent?: AlignContent;
    /** CSS `align-items` */
    alignItems?: AlignItems;
    /** CSS `align-self` */
    alignSelf?: AlignSelf;

    /** CSS `display` */
    display?: Display;
    /** CSS `flex` (shorthand for `flex-grow`, `flex-shrink`, `flex-basis`) */
    flex?: Flex;
    /** CSS `flex-direction` */
    flexDirection?: FlexDirection;
    /** CSS `flex-wrap` */
    flexWrap?: FlexWrap;

    /** CSS `justify-content` */
    justifyContent?: JustifyContent;
    /** CSS `justify-items` */
    justifyItems?: JustifyItems;
    /** CSS `justify-self` */
    justifySelf?: JustifySelf;

    // ────────────────────────────────────────────────────────────
    // Position & Overflow
    // ────────────────────────────────────────────────────────────

    /** CSS `position` */
    position?: Position;

    /** CSS `overflow` */
    overflow?: Overflow;
    /** CSS `overflow-x` */
    overflowX?: Overflow;
    /** CSS `overflow-y` */
    overflowY?: Overflow;
}>;

export type BoxProps<T extends React.ElementType = "div"> = BoxOwnProps &
    Omit<React.ComponentPropsWithoutRef<T>, keyof BoxOwnProps>;

/**
 * Polymorphic component signature for the `<Box>` component.
 *
 * We model this component as a generic function so that the consumer can swap
 * out the underlying element via the `as` prop **and** still benefit from the
 * correct DOM attribute typings for that element.
 */
export type BoxComponent = (<T extends React.ElementType = "div">(
    props: BoxProps<T> & { as?: T } & React.RefAttributes<React.ElementRef<T>>,
) => React.ReactElement | null) & { displayName?: string };
