#!/usr/bin/env node
/**
 * @license Copyright 2017 Palantir Technologies, Inc. All rights reserved.
 * @fileoverview Finds the subset of packages which are ready to be published based on the latest Lerna publish commit.
 */

"use strict";

// @ts-check

const cp = require("child_process");
const path = require("path");
const yargs = require("yargs").usage("$0 <commitish>").help();

const args = yargs.argv;
const commitish = args._[0] || "HEAD";

cp.exec(`git tag --points-at ${commitish}`, (err, stdout) => {
    if (err) {
        throw err;
    }

    const taggedPackageNames = stdout
        .toString()
        .split("\n")
        .map(line => line.trim())
        .filter(line => line.length > 0)
        .map(tag => {
            const match = /^(.+)\@([^@]+)$/.exec(tag);
            if (!match) {
                return null;
            } else {
                return match[1];
            }
        })
        .filter(name => name != null);

    const publishablePackagePaths = taggedPackageNames
        .map(name => {
            const nameParts = name.split("/");
            const unscopedName = nameParts[nameParts.length - 1];
            const packagePath = path.join("packages", unscopedName);
            return {
                // This will throw if the package name isn't also the path, which is desirable.
                packageJson: require(path.resolve(packagePath, "package.json")),
                path: packagePath,
            };
        })
        .filter(({ packageJson }) => !packageJson.private)
        .map(pkg => pkg.path);

    publishablePackagePaths.forEach(pkgPath => console.info(pkgPath));
});
