#!/bin/bash

set -ex
set -o pipefail

git fetch --tags

SCRIPTS_DIR="$( dirname "$(readlink -f "$0")" )"

publishable_paths=$("$SCRIPTS_DIR/get-publishable-paths-from-semver-tags" --npm | sed -E -e '/^ *$/d')
for path in $publishable_paths; do
  pushd "$path"
  "$SCRIPTS_DIR/circle-publish-npm"
  popd
done
