#!/usr/bin/env bash

# Submits a comment to the change PR or commit with links to artifcats that show the results of the
# code change being applied.

source scripts/artifact-variables

findBuildArtifacts

# Docs
echo "Docs preview...RENDER"
PREVIEWS="$(artifactLink 'packages/docs-app' 'documentation')"

# Landing
echo -n "landing-app preview..."
git diff HEAD..origin/master --quiet -- packages/landing-app
if [ $? -eq 0 ]; then
    echo "SKIP"
else
    echo "RENDER"
    PREVIEWS="$PREVIEWS | $(artifactLink 'packages/landing-app' 'landing')"
fi

# Table
echo -n "Table preview..."
git diff HEAD..origin/master --quiet -- packages/table
if [ $? -eq 0 ]; then
    echo "SKIP"
else
    echo "RENDER"
    PREVIEWS="$PREVIEWS | $(artifactLink 'packages/table-dev-app' 'table')"
fi

# Actual public site
echo -n "Full site preview..."
git rev-parse --abbrev-ref HEAD | grep -q -e '^release/'
if [ $? -eq 0 ]; then
    echo "RENDER"
    PREVIEWS="$PREVIEWS | $(artifactLink 'docs/v2/index' 'github pages')"
else
    echo "SKIP"
fi

# Submit comment
submitPreviewComment "<h3>${COMMIT_MESSAGE}</h3>\n\nPreview: <strong>${PREVIEWS}</strong>"
