#!/usr/bin/env bash

# Submits a comment to the change PR or commit with links to artifcats that show the results of the
# code change being applied.

source scripts/artifact-variables

# Docs
echo "Docs preview...RENDER"
PREVIEWS="$(artifactLink '/packages/docs-app/dist/index.html' 'documentation')"
COVERAGES="$(coverageLink '/packages/core/' 'core')"
COVERAGES="$COVERAGES | $(coverageLink 'packages/datetime/' 'datetime')"

# Landing
echo -n "landing-app preview..."
git diff HEAD..origin/master --quiet -- packages/landing-app
if [ $? -eq 0 ]; then
    echo "SKIP"
else
    echo "RENDER"
    (cd packages/landing-app; npm run build)
    PREVIEWS="$PREVIEWS | $(artifactLink '/packages/landing-app/dist/index.html' 'landing')"
fi

# Table
echo -n "Table preview..."
git diff HEAD..origin/master --quiet -- packages/table
if [ $? -eq 0 ]; then
    echo "SKIP"
else
    echo "RENDER"
    (cd packages/table; npm run build)
    PREVIEWS="$PREVIEWS | $(artifactLink '/packages/table/dist/preview/index.html' 'table')"
fi

# Actual public site
echo -n "Full site preview..."
git rev-parse --abbrev-ref HEAD | grep -q -e '^release/'
if [ $? -eq 0 ]; then
    git diff HEAD..origin/master --quiet -- docs
    if [ $? -eq 0 ]; then
        echo "ERROR"
        echo "New release detected, but docs were not updated."
        exit 1
    else
        echo "DONE"
        PREVIEWS="$PREVIEWS | $(artifactLink '/docs/index.html' 'github pages')"
    fi
else
    echo "SKIP"
fi

# Submit comment
submitPreviewComment "<h3>${COMMIT_MESSAGE}</h3>\n\nPreview: <strong>${PREVIEWS}</strong>\nCoverage: ${COVERAGES}"
